### ISSUE TITLE
Extra threads in sequences.crf

### ISSUE THREAD

**Issue by dcdowney** [allenai/ml#14]
Run ...sequences.crf.conll.ConllCRFEndToEndTest.testEndToEnd(), the code creates ~40 threads that remain running at the end of the call.  

In my tests this results in the VM not exiting even after the test code terminates (although it appears that Gradle's testing eventually does shut all the threads down, so the Gradle tests succeed (?)).

The reason I think is invocations like this one (line 43 in conll.Evaluator.java):
double acc = Evaluation.compute(crf, evalData, Parallel.MROpts.withThreads(1)).tokenAccuracy.accuracy();

where the executorService created in the MROpts object never gets shutdown().

**Comment by aria42** [comment]
I see the issue, but patching that didn't do it, I think the executor services aren't shutting down

**Comment by aria42** [comment]
Ok, I have a PR and I've assigned you to review. The test now checks there aren't stray MR threads.

**Comment by aria42** [comment]
It turns out there were a bunch of spots not shutting down the thread-pool.

**Comment by dcdowney** [comment]
New code checked out fine, so I went ahead and did the merge.

**Comment by aria42** [comment]
Shoot, one of the tests was still pending and failed. I'll do another PR to fix the failign test.

**Comment by aria42** [comment]
Did this fix your issue @dcdowney? The thread count should be 10 or so because of the shared JVM ForkJoin pool, but we can't control that.

**Comment by dcdowney** [comment]
Yep, JVM shuts down normally now, so I think we're in good shape.  Thanks!
